config/routes.rb
Golf::Application.routes.draw do
  get "image/index"
  get "image/new"
  get "image/edit"
  get "welcome/index"

  root 'welcome#index'

  resources :blogs
  resources :tournaments
  resources :game
  resources :gallery do
    get :raise_counter
  end
  resources :image

  resources :user do
    put :add_admin
    put :remove_admin
  end

  
  resources :session, only: [:new, :create, :destroy]
  match '/signup',  to: 'user#new',            via: 'get'
  match '/signin',  to: 'session#new',         via: 'get'
  match '/signout', to: 'session#destroy',     via: 'delete'
  match '/admin',   to: 'user#admin',          via: 'get'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :galleries
	attr_reader :galleries_tokens
	has_attached_file :photo,
		:styles => {:preview => ['900x300#'], :frontpage => ['700x400#']},
		:path => ":rails_root/public/data/photos/blogs/:id/:basename_:style.:extension",
		:url => "/data/photos/blogs/:id/:basename_:style.:extension"
		#:path => ":rails_root/public/data/photos/1/subpage-banner.jpg",
		#:url => "/data/photos/1/subpage-banner.jpg"
	#validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	
	validates_attachment :photo,
    	:presence => true,
    	content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }


    def galleries_tokens=(ids)
    	galleries_ids = ids.split(",")
    	self.galleries = []
    	
    	for id in galleries_ids
    		self.galleries << Gallery.find_by_id(id)
    	end
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	include BlogsHelper
	def index
		@blogs = Blog.find(:all, :order => "created_at desc")
	end

	def new
		if !current_user
			redirect_to root_path
		end
	end

	def update
		blog = Blog.find(params[:id])
		if has_access(blog,current_user)
			blog.update_attributes(blog_params)
			redirect_to blogs_path
		else
			redirect_to blogs_path
		end
	end

	def edit
		@blog = Blog.find(params[:id])
		if !has_access(@blog, current_user)
			redirect_to blogs_path
		end
	end

	def destroy
		@blog = Blog.find(params[:id])
		if has_access(@blog, current_user)
			@blog.destroy
			redirect_to blogs_path
		else
			redirect_to blogs_path
		end
	end

	def create
		@blog = Blog.new(blog_params)
		@blog.user_id = current_user.id
		if @blog.save
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def show
		@blog = Blog.find(params[:id])
		@blog.viewed += 1
		@blog.save
	end

	private

	def blog_params
		params.require(:blog).permit(:title, :text, :photo, :galleries_tokens)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def has_access(blog, user)
  	if (blog.user_id == user.id) || (is_admin(user))
  		return true
  	else
  		return false
  	end
  end

  def is_admin(user)
  	return user.admin
  end
end

app/views/blogs/edit.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>New Blog</h1>
    <%= form_for @blog, url: {action: "update"}, html: {:multipart => true} do |f| %>
      <p>
        <%= f.label 'Title:' %><br/>
        <%= f.text_field :title, :required => true, class: "form-control" %>
      </p>
      <p>
        <%= f.label 'Text:' %><br/>
        <%= f.text_area :text, :required => true, rows: 10, class: "form-control" %>  </p>
      </p>
      <p>
        <%= f.label 'Myndaalbúm:' %><br/>
        <%= f.text_field :galleries_tokens, "data-pre" => @blog.galleries.to_json, class: "form-control" %>  </p>
      </p>
      <p>
        <%= f.file_field :photo %>
      </p>
      <p>
        <%= f.submit 'Create', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Clear Form', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

<script type="text/javascript">
 $(function() {
    $("#blog_galleries_tokens").tokenInput("/gallery.json", {
      crossDomain: false,
      prePopulate: $("#blog_galleries_tokens").data("pre")
    });
 });
</script>

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home Template for Bootstrap 3</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/blog-home.css" rel="stylesheet">

</head>

<body>

   

    <div class="container" style="margin-top: 60px;">

        <div class="row">
            <div class="col-lg-8">

                <% @blogs.each do |blog| %>

                <!-- blog entry -->
                <h1><%= link_to blog.title, blog_path(blog.id), {method: :get} %></a>
                </h1>
                <p class="lead">Höfundur: <%=blog.user.fullname%>
                </p>
                <p>
                    <span class="glyphicon glyphicon-time"></span> <%=blog.created_at.strftime("Skrifað þann %m/%d/%Y, klukkan %H:%M")  %></p>
                <hr>
                <%= image_tag blog.photo.url(:preview), :class => "img-responsive" %>
                <br>
                <p><%=truncate blog.text, length: 400 %></p>
                
                <%if current_user && has_access(blog,current_user)%>
                <%= button_to "Lesa meira", blog_path(blog.id), {method: :get, class: "btn btn-primary", style:"float:left; margin-right:15px;"} %>
                <%= button_to "Breyta frétt", edit_blog_path(:id => blog.id), {method: :get, class: "btn btn-primary", style:"float:left; margin-right:15px;"} %>
                    <%= button_to "Eyða frétt", blog_path(:id => blog.id), {method: :delete, class: "btn btn-danger"} %> 
                <%else%>
                <%= button_to "Lesa meira", blog_path(blog.id), {method: :get, class: "btn btn-primary"} %>
                <%end%>

                <hr style="margin-bottom:70px;">
                <% end %>


                <!-- pager -->
                <!--<ul class="pager">
                    <li class="previous"><a href="#">&larr; Older</a>
                    </li>
                    <li class="next"><a href="#">Newer &rarr;</a>
                    </li>
                </ul>-->

            </div>

            <div class="col-lg-4" style="margin-top: 60px;">
                
                <div class="col-lg-12">
                    <div class="well">
                        <h4>Leita að frétt</h4>
                        <div class="input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <span class="glyphicon glyphicon-search"></span>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </div>
                </div>
                <% if current_user %>
                <div class="col-lg-12">
                    <p><%= button_to "Ný frétt", new_blog_path, {method: :get, class: "btn btn-primary"} %></p>
                </div>
                <% end%>
                <!-- /well -->
                <!--<div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>-->
                <!-- /well -->
                <!--<div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>-->
                <!-- /well -->
            </div>
        </div>

        <hr>

        <!--<footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>-->

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

</body>

</html>

app/views/blogs/new.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>New Blog</h1>
    <%= form_for :blog, url: {action: "create"}, html: {:multipart => true} do |f| %>
      <p>
        <%= f.label 'Title:' %><br/>
        <%= f.text_field :title, :required => true, class: "form-control" %>
      </p>
      <p>
        <%= f.label 'Text:' %><br/>
        <%= f.text_area :text, :required => true, rows: 10, class: "form-control" %>  </p>
      </p>
      <p>
        <%= f.label 'Myndaalbúm:' %><br/>
        <%= f.text_field :galleries_tokens, class: "form-control" %>  </p>
      </p>
      <p>
        <%= f.file_field :photo, :required => true %>
      </p>
      <p>
        <%= f.submit 'Create', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Clear Form', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

<script type="text/javascript">
 $(function() {
    $("#blog_galleries_tokens").tokenInput("/gallery.json", {
      crossDomain: false,
      theme: 'facebook'
    });
 });
</script>

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post Template for Bootstrap 3</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/blog-post.css" rel="stylesheet">
    <style>
        #galleria{height:567px}
    </style>

</head>

<body>

   

    <div class="container" style="margin-top: 60px;">

        <div class="row">
            <div class="col-lg-12">
                <h1><%=@blog.title%></h1>
                <p class="lead">Höfundur: <%=@blog.user.fullname%>
                </p>
                <hr>
                <p>
                    <span class="glyphicon glyphicon-time"></span> <%=@blog.created_at.strftime("Skrifað þann %m/%d/%Y, klukkan %H:%M")  %></p>
                <hr>
            </div>
            <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                
                <a href="#myModal2" data-toggle="modal"><%= image_tag @blog.photo.url(:frontpage), :class => "img-responsive" %></a>
                <hr>
                <p><%=simple_format(@blog.text)%></p>

                <hr>

                <%if current_user && has_access(@blog,current_user)%>
                    <%= button_to "Breyta frétt", edit_blog_path(:id => @blog.id), {method: :get, class: "btn btn-primary", style:"float:left; margin-right:15px;"} %>
                    <%= button_to "Eyða frétt", blog_path(:id => @blog.id), {method: :delete, class: "btn btn-danger"} %> 
                <% end %>

                <!-- the comment box -->
                <!--<div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>-->


                <!-- the comments -->
                <!--<h3>Start Bootstrap
                    <small>9:41 PM on August 24, 2013</small>
                </h3>
                <p>This has to be the worst blog post I have ever read. It simply makes no sense. You start off by talking about space or something, then you randomly start babbling about cupcakes, and you end off with random fish names.</p>

                <h3>Start Bootstrap
                    <small>9:47 PM on August 24, 2013</small>
                </h3>
                <p>Don't listen to this guy, any blog with the categories 'dinosaurs, spaceships, fried foods, wild animals, alien abductions, business casual, robots, and fireworks' has true potential.</p>-->

            </div>

            <% if @blog.galleries.count > 0 %>
                <div class="col-lg-4">
                    <div class="lead col-md-12 portfolio-item">Tengd myndaalbúm: </div>

                    <% @blog.galleries.each_with_index do |gallery, index| %>
                        <div class="col-md-12 portfolio-item" style="margin-bottom:60px;">
                             <div class="thumbnail">
                                <a href="#project-link" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);">
                                    <%= image_tag gallery.photo.url(:preview), :class => "img-responsive" %>
                                </a>
                                <h3><a href="#project-link" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);"><%=gallery.name%></a>
                                </h3>
                                <p>
                                    <span class="glyphicon glyphicon-time"></span> <%=gallery.created_at.strftime("Sett inn %m/%d/%Y, klukkan %H:%M")  %></p> <hr>
                                    <p style = "height: 60px;"><%= gallery.description %></p>
                                    <div style = "height: 40px;">
                                        <p><button class="btn btn-primary" style="float:left; margin-right:15px;" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);">Skoða</button>
                                        </p>
                                    <%if current_user && has_access(gallery, current_user)%>
                                        
                                        <%#= button_to "Breyta", edit_gallery_path(:id => gallery.id), {method: :get, class: "btn btn-primary", style:"float:left; margin-right:15px;"} %>

                                        <%#= button_to "Eyða", gallery_path(:id => gallery.id), {method: :delete, class: "btn btn-danger"} %>
                                        
                                    <%end%>
                                    </div>
                                </div>
                        </div>
                    <% end %>
                </div>
            <% end %>

            <!--<div class="col-lg-4">
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>-->
                    <!-- /input-group -->
                <!--</div>-->
                <!-- /well -->
                <!--<div class="well">
                    <h4>Popular Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#dinosaurs">Dinosaurs</a>
                                </li>
                                <li><a href="#spaceships">Spaceships</a>
                                </li>
                                <li><a href="#fried-foods">Fried Foods</a>
                                </li>
                                <li><a href="#wild-animals">Wild Animals</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#alien-abductions">Alien Abductions</a>
                                </li>
                                <li><a href="#business-casual">Business Casual</a>
                                </li>
                                <li><a href="#robots">Robots</a>
                                </li>
                                <li><a href="#fireworks">Fireworks</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>-->
                <!-- /well -->
                <!--<div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Bootstrap's default wells work great for side widgets! What is a widget anyways...?</p>
                </div>-->
                <!-- /well -->
            <!--</div>
        </div>-->

        <hr>



        <!--<footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>-->

    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-lg-12">
                    <div id="galleria">
                            <!--<img src="/IMG_0321.jpg">
                            <img src="/IMG_0330.jpg">-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Loka</button>
                <button id="fullscreen" type="button" class="btn btn-success">Fullscreen</button>
            </div>
        </div>
    </div>
    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

    

<script type="text/javascript">

    $('#galleria').galleria({
        width: 700,
        height: 407 //--I made heights match
    });


    $('#fullscreen').click(function() {
        $('#galleria').data('galleria').toggleFullscreen(); // toggles the fullscreen
    });

    window.onload = function() {
      loadGalleria(72157612108853933);
    };

    function loadGalleria(set) {
        var setString = 'set:' + set;
        //alert(setString);
        Galleria.loadTheme('/galleria.classic.min.js');
                //Galleria.run('#galleria');
        Galleria.run('#galleria', {
            flickr: setString,
            flickrOptions: {
                max: 400,
                sort: 'date-posted-asc'
            }
        });
    }

    function modalClick(title,gallery_id) {  
        
        $.ajax({
            url: "/gallery/"+gallery_id+"/raise_counter",
            dataType: "html",
            data: {
                gallery_id: gallery_id
            },
            type: 'GET',
            success: function( data ) {
                $("#myModalLabel").text(title);
                $('#myModal').modal('toggle');
            },
              error: function(){

              }



        }); 
    }

</script>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModal2Label" aria-hidden="true">
  <div class="modal-dialog">
    <%= image_tag @blog.photo.url(:original), :class => "img-responsive" %>
  </div>
</div>

</body>

</html>