config/routes.rb
Golf::Application.routes.draw do
  get "image/index"
  get "image/new"
  get "image/edit"
  get "welcome/index"

  root 'welcome#index'

  resources :blogs
  resources :tournaments
  resources :game
  resources :gallery do
    get :raise_counter
  end
  resources :image

  resources :user do
    put :add_admin
    put :remove_admin
  end

  
  resources :session, only: [:new, :create, :destroy]
  match '/signup',  to: 'user#new',            via: 'get'
  match '/signin',  to: 'session#new',         via: 'get'
  match '/signout', to: 'session#destroy',     via: 'delete'
  match '/admin',   to: 'user#admin',          via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :tournaments
	before_create :create_remember_token
	has_attached_file :photo,
		:styles => {:frontpage => ['700x700#']},
		:path => ":rails_root/public/data/photos/users/:id/:basename_:style.:extension",
		:url => "/data/photos/users/:id/:basename_:style.:extension"
		#:path => ":rails_root/public/data/photos/1/subpage-banner.jpg",
		#:url => "/data/photos/1/subpage-banner.jpg"
	#validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	
	validates_attachment :photo,
    	#:presence => true,
    	content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

	def create_remember_token
		self.remember_token = User.hash(User.new_remember_token)
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	include UserHelper
	def index
		@users = User.where("fullname like ?", "%#{params[:q]}%").order("created_at desc")
	    respond_to do |format|
	      format.html
	      format.json { render :json => @users }
	    end
	end

	def create
		if current_user && is_admin(current_user)
			hashed_pw = Digest::SHA1.hexdigest("123")
		  	@user = User.new(user_params)
		  	@user.password = hashed_pw
		    @user.admin = false

		    if @user.save
		      redirect_to root_path
		    else
		      render 'new'
		    end
		else
			redirect_to root_path
		end

  	#@user.save!
  	#redirect_to users_path()
  end

  def admin
  	if current_user && is_admin(current_user)
  		@users = User.all(:order => "fullname ASC")
  		@images = Image.all()
  	else
  		redirect_to root_path
  	end
  end

  def update
  	if current_user
	  	user = User.find(params[:id])
	  	if !user_params[:password].empty?
	  		hashed_pw = Digest::SHA1.hexdigest(user_params[:password])
		  	#user_params[:password] = hashed_pw
			user.password = hashed_pw
		end
		if !user_params[:photo].nil?
			user.photo = user_params[:photo]
		end
		user.description = user_params[:description]

		user.save!
		redirect_to root_path
	else
		redirect_to root_path
	end
  end

  def edit
  	if current_user
		@user = User.find(params[:id])
	else
		redirect_to root_path
	end
		
	end

  def add_admin
  	if current_user && is_admin(current_user)
	  	user = User.find(params[:user_id])
	  	user.admin = true
	  	user.save!
	  	redirect_to admin_path
	  else
	  	redirect_to root_path
	  end
  end

  def remove_admin
  	if current_user && is_admin(current_user)
	  	user = User.find(params[:user_id])
	  	user.admin = false
	  	user.save!
	  	redirect_to admin_path
	  else
	  	redirect_to root_path
	  end
  end

  private

  def user_params
  	params.require(:user).permit(:username, :fullname, :password, :email, :admin, :photo, :description, :sign_in_counter)
  end
end

app/helpers/user_helper.rb
module UserHelper
	def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def has_access(blog, user)
  	if (blog.user_id == user.id) || (is_admin(user))
  		return true
  	else
  		return false
  	end
  end

  def is_admin(user)
  	return user.admin
  end
end

app/views/user/admin.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-12">
    <table class="tablesorter table table-hover"  id="user_list">
      <thead class="table-header fixedHeader">
        <tr colspan="8">
        <th>Nafn</th>
        <th>Notendanafn</th>
        <th>Stjórnandi</th>
        <th>Breyta</th>
        </tr>
      </thead>

      <h2>Notandalisti</h2>
      <tbody id="operationlist" class="scrollContent">
      <% @users.each do |user| %>

        <tr>
          <td style="width:auto;"><%=user.fullname%></td>
          <td style="width:auto;"><%=user.username%></td>
          <% if user.admin %>
            <td style="width:auto;"><%= button_to "Já", user_remove_admin_path(:user_id => user.id), {method: :put, class: "btn btn-primary"} %></td>
          <% else %>
            <td style="width:auto;"><%= button_to "Nei", user_add_admin_path(:user_id => user.id), {method: :put, class: "btn btn-default"} %></td>
          <% end %>
          <td style="width:auto;"><%= button_to "Breyta", edit_user_path(:id => user.id), {method: :get, class: "btn btn-default"} %></td>

        </tr>

      <% end %>
      </tbody>
    </table>
<%= button_to "Nýr notandi", signup_path, {method: :get, class: "btn btn-success"} %>
  <br><br>
    <h2>Myndalisti</h2>
    <table class="tablesorter table table-hover"  id="user_list">
      <thead class="table-header fixedHeader">
        <tr colspan="8">
        <th>Lýsing</th>
        <th>Breyta</th>
        </tr>
      </thead>

      <tbody id="operationlist" class="scrollContent">
      <% @images.each do |image| %>

        <tr>
          <td style="width:auto;"><%=image.description%></td>
          <td style="width:auto;"><%= button_to "Breyta", edit_image_path(:id => image.id), {method: :get, class: "btn btn-default"} %></td>

        </tr>

      <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/user/edit.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>Breyta lykilorði notanda</h1>
    <%= form_for @user, url: {action: "update"}, html: {:multipart => true} do |f| %>
      <p>
        <%= f.label 'fullname:' %><br/>
        <%= f.text_field :fullname, :required => true, class: "form-control" %>  </p>
      <p>
        <%= f.label 'email:' %><br/>
        <%= f.text_field :email, :required => true, class: "form-control" %>  </p>
      <p>
        <%= f.label 'Description:' %><br/>
        <%= f.text_area :description, :required => true, rows: 10, class: "form-control" %>  </p>
      <p>
      <%= f.file_field :photo %>
      </p>
      <p>
        <%= f.label 'password:' %><br/>
        <%= f.password_field :password, class: "form-control"%>
      </p>
      <p>
        <%= f.label 'password confirmation:' %><br/>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>
      <p>
        <%= f.submit 'Create', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Clear Form', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/user/new.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>Sign Up</h1>
    <%= form_for :user, url: {action: "create"} do |f| %>
      <p>
        <%= f.label 'username:' %><br/>
        <%= f.text_field :username, :required => true, class: "form-control" %>
      </p>
      <p>
        <%= f.label 'fullname:' %><br/>
        <%= f.text_field :fullname, :required => true, class: "form-control" %>  </p>
      <p>
      <p>
        <%= f.label 'email:' %><br/>
        <%= f.text_field :email, :required => true, class: "form-control" %>  </p>

       <p>
        <%= f.label 'Description:' %><br/>
        <%= f.text_area :description, :required => true, rows: 10, class: "form-control" %>  </p>
    
      <p>
        <%= f.file_field :photo, :required => true %>
      </p>
      <!--<p>
        <%= f.label 'password:' %><br/>
        <%= f.password_field :password, class: "form-control"%>
      </p>
      <p>
        <%= f.label 'password confirmation:' %><br/>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>-->
      <p>
        <%= f.submit 'Sign Up', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Clear Form', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>