config/routes.rb
Golf::Application.routes.draw do
  get "image/index"
  get "image/new"
  get "image/edit"
  get "welcome/index"

  root 'welcome#index'

  resources :blogs
  resources :tournaments
  resources :game
  resources :gallery do
    get :raise_counter
  end
  resources :image

  resources :user do
    put :add_admin
    put :remove_admin
  end

  
  resources :session, only: [:new, :create, :destroy]
  match '/signup',  to: 'user#new',            via: 'get'
  match '/signin',  to: 'session#new',         via: 'get'
  match '/signout', to: 'session#destroy',     via: 'delete'
  match '/admin',   to: 'user#admin',          via: 'get'

  

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :blogs
	has_and_belongs_to_many :tournaments
	has_attached_file :photo,
		:styles => {:preview => ['700x400#'], :frontpage => ['700x400#']},
		:path => ":rails_root/public/data/photos/galleries/:id/:basename_:style.:extension",
		:url => "/data/photos/galleries/:id/:basename_:style.:extension"
		#:path => ":rails_root/public/data/photos/1/subpage-banner.jpg",
		#:url => "/data/photos/1/subpage-banner.jpg"
	#validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	
	validates_attachment :photo,
    	:presence => true,
    	content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  include GalleryHelper
  def index
  	#@galleries = Gallery.find(:all, :order => "created_at desc")
    @galleries = Gallery.where("name like ?", "%#{params[:q]}%").order("created_at desc")
    respond_to do |format|
      format.html
      format.json { render :json => @galleries }
    end
  end

  def raise_counter
    gallery = Gallery.find(params[:gallery_id])
    if (!current_user) || (current_user.id != gallery.user_id)
      gallery.viewed += 1
      gallery.save
    end

    redirect_to :back
  end

  def new
    if !current_user
      redirect_to root_path
    end
  end

  def update
    gallery = Gallery.find(params[:id])
    if has_access(gallery, current_user)
      gallery.update_attributes(gallery_params)
      redirect_to gallery_index_path
    else
      redirect_to gallery_index_path
    end
  end

  def edit
    if current_user
      @gallery = Gallery.find(params[:id])
    else
      redirect_to gallery_index_path
    end
  end

  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id = current_user.id
    if @gallery.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    if has_access(@gallery, current_user)
      @gallery.destroy
      redirect_to gallery_index_path
    else
      redirect_to gallery_index_path
    end
  end

  private

  def gallery_params
   params.require(:gallery).permit(:name, :description, :setid, :photo)
 end
end

app/helpers/gallery_helper.rb
module GalleryHelper
	def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def has_access(gallery, user)
  	if (gallery.user_id == user.id) || (is_admin(user))
  		return true
  	else
  		return false
  	end
  end

  def is_admin(user)
  	return user.admin
  end
end

app/views/gallery/edit.html.erb
<div class="container" style="margin-top: 60px;">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>New Gallery</h1>
    <%= form_for @gallery, url: {action: "update", controller: "gallery"}, html: {:multipart => true} do |f| %>
      <p>
        <%= f.label 'Name:' %><br/>
        <%= f.text_field :name, :required => true, class: "form-control" %>
      </p>
      <p>
        <%= f.label 'Set-id:' %><br/>
        <%= f.text_field :setid, :required => true, class: "form-control" %>  
      </p>
      <p>
        <%= f.label 'Description:' %><br/>
        <%= f.text_area :description, :required => true,  :maxlength => 115, rows: 3, class: "form-control" %>  
      </p>
      <% if !@gallery.photo.nil? || !@gallery.photo.empty? %>
        Mynd upphlaðin
      <% end %>
      <p>
        <%= f.file_field :photo %>
      </p>
      <!--<p>
        <%= f.file_field :photo %>
      </p>-->
      <p>
        <%= f.submit 'Vista', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Hreinsa', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/gallery/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/full-slider.css" rel="stylesheet">
    <style>
        #galleria{height:407px}
    </style>

</head>

<body style="margin-top: 100px;">

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <%if current_user%>
                <div class="col-lg-4">

                    <div class="col-lg-12">
                        <div class="well">
                            <h4>Leita að Myndaalbúmi</h4>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>

                        </div>
                    </div>
                    <% if current_user %>
                    <div class="col-lg-12">
                        <p><%= button_to "Nýtt myndaalbúm", new_gallery_path, {method: :get, class: "btn btn-primary"} %></p>
                    </div>
                    <% end%>
                </div>
                <% end %>

                <% @galleries.each_with_index do |gallery, index| %>
                <div class="col-md-4 portfolio-item" style="margin-bottom:60px;">
                 <div class="thumbnail">
                    <a href="#project-link" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);">
                        <%= image_tag gallery.photo.url(:preview), :class => "img-responsive" %>
                    </a>
                    <h3><a href="#project-link" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);"><%=gallery.name%></a>
                    </h3>
                    <p>
                        <span class="glyphicon glyphicon-time"></span> <%=gallery.created_at.strftime("Sett inn %m/%d/%Y, klukkan %H:%M")  %></p> <hr>
                        <p style = "height: 60px;"><%= gallery.description %></p>
                        <div style = "height: 40px;">
                            <p><button class="btn btn-primary" style="float:left; margin-right:15px;" onclick="loadGalleria('<%=gallery.setid%>');modalClick('<%=gallery.name%>',<%=gallery.id%>);">Skoða</button>
                            </p>
                        <%if current_user && has_access(gallery, current_user)%>
                            
                            <%= button_to "Breyta", edit_gallery_path(:id => gallery.id), {method: :get, class: "btn btn-primary", style:"float:left; margin-right:15px;"} %>

                            <%= button_to "Eyða", gallery_path(:id => gallery.id), {method: :delete, class: "btn btn-danger"} %>
                            
                        <%end%>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        <!--<div class="col-lg-4">

            <div class="col-lg-12">
                <div class="well">
                    <h4>Leita að Myndaalbúmi</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>

                </div>
            </div>
            <% if current_user %>
            <div class="col-lg-12">
                <p><%= button_to "Nýtt myndaalbúm", new_gallery_path, {method: :get, class: "btn btn-primary"} %></p>
            </div>
            <% end%>
        </div>-->
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <div id="galleria">
                        <!--<img src="/IMG_0321.jpg">
                        <img src="/IMG_0330.jpg">-->
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Loka</button>
            <button id="fullscreen" type="button" class="btn btn-success">Fullscreen</button>
        </div>
    </div>
</div>
</div>

</body>
</html>

<script type="text/javascript">
    $('#galleria').galleria({
        width: 700,
        height: 407 //--I made heights match
    });


    $('#fullscreen').click(function() {
        $('#galleria').data('galleria').toggleFullscreen(); // toggles the fullscreen
    });

    window.onload = function() {
      loadGalleria(72157612108853933);
    };

    function loadGalleria(set) {
        var setString = 'set:' + set;
        //alert(setString);
        Galleria.loadTheme('/galleria.classic.min.js');
                //Galleria.run('#galleria');
        Galleria.run('#galleria', {
            flickr: setString,
            flickrOptions: {
                max: 400,
                sort: 'date-posted-asc'
            }
        });
    }

    function modalClick(title,gallery_id) {  
        
        $.ajax({
            url: "/gallery/"+gallery_id+"/raise_counter",
            dataType: "html",
            data: {
                gallery_id: gallery_id
            },
            type: 'GET',
            success: function( data ) {
                $("#myModalLabel").text(title);
                $('#myModal').modal('toggle');
            },
              error: function(){

              }



        }); 
    }

    </script>

app/views/gallery/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <style>
        #galleria{height:407px}
    </style>
</head>

<body style="margin-top: 60px;">

<div class="container">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>New Gallery</h1>
    <%= form_for :gallery, url: {action: "create"}, html: {:multipart => true} do |f| %>
      <p>
        <%= f.label 'Name:' %><br/>
        <%= f.text_field :name, :required => true, class: "form-control" %>
      </p>
      <p>
        <%= f.label 'Set-id:' %><br/>
        <%= f.text_field :setid, :required => true, class: "form-control" %>  
      </p>
      <p>
      <a class="btn btn-default" href="#project-link" onclick="loadGalleria();modalClick();">Skoða myndir</a>
      </p>
      <p>
        <%= f.label 'Description:' %><br/>
        <%= f.text_area :description, :required => true, :maxlength => 115, rows: 3, class: "form-control" %>  
      </p>
      <p>
        <%= f.file_field :photo, :required => true %>
      </p>
      <!--<p>
        <%= f.file_field :photo %>
      </p>-->
      <p>
        <%= f.submit 'Vista', class: "btn btn-success" %>&nbsp;&nbsp;&nbsp;
        <%= f.submit 'Hreinsa', class: "btn btn-default", :type => 'reset' %>
      </p>
    <% end %>

    
  </div>
  <div class="col-md-4">
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
        
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <div id="galleria">
                        <!--<img src="/IMG_0321.jpg">
                        <img src="/IMG_0330.jpg">-->
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Loka</button>
            <button id="fullscreen" type="button" class="btn btn-success">Fullscreen</button>
        </div>
    </div>
</div>
</div>
</body>
</html>

<script type="text/javascript">
  window.onload = function() {
      loadGalleria(72157612108853933);
    };

    $('#galleria').galleria({
        width: 700,
        height: 407 //--I made heights match
    });


  function loadGalleria(set) {
        var setString = 'set:' + document.getElementById("gallery_setid").value;
        //alert(setString);
        Galleria.loadTheme('/galleria.classic.min.js');
                //Galleria.run('#galleria');
        Galleria.run('#galleria', {
            flickr: setString,
            flickrOptions: {
                max: 400,
                sort: 'date-posted-asc'
            }
        });
    }

  function modalClick() {  
        $('#myModal').modal('toggle');
    }
</script>