config/routes.rb
Golf::Application.routes.draw do
  get "image/index"
  get "image/new"
  get "image/edit"
  get "welcome/index"

  root 'welcome#index'

  resources :blogs
  resources :tournaments
  resources :game
  resources :gallery do
    get :raise_counter
  end
  resources :image

  resources :user do
    put :add_admin
    put :remove_admin
  end

  
  resources :session, only: [:new, :create, :destroy]
  match '/signup',  to: 'user#new',            via: 'get'
  match '/signin',  to: 'session#new',         via: 'get'
  match '/signout', to: 'session#destroy',     via: 'delete'
  match '/admin',   to: 'user#admin',          via: 'get'

  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-custom" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%=root_path()%>">Hansen Open</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Fréttir", blogs_path(), {method: :get} %>
                    </li>
                    <li><%= link_to "Myndasöfn", gallery_index_path(), {method: :get} %>
                    </li>
                    <li><%= link_to "Keppnir", tournaments_path(), {method: :get} %>
                    </li>
                    <% if !current_user %> 
                        <li><%= link_to "Skrá inn", signin_path(), {method: :get} %>
                        </li>
                    <%end%>
                    <% if current_user %>
                        <li><%= link_to "Skrá út", signout_path(), {method: :delete} %>
                        </li>
                        <% if is_admin(current_user)%>
                        <li><%= link_to "Admin", admin_path(), {method: :get} %>
                        </li>
                        <%end%>
                        
                        <li><%= link_to "Breyta lykilorði", edit_user_path(:id => current_user.id), {method: :get} %>
                        </li>
                    <%end%>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hansen Open</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<header>
    
      <%= render 'layouts/header' %>
  </header>

<%= yield %>

</body>
</html>

<script type="text/javascript">
	window.onload = function() {
	      Galleria.loadTheme('/galleria.classic.min.js');
	    };

  <% if (request.original_url.include? "hansenopen") %>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-54621282-1', 'auto');
    ga('send', 'pageview');
  <% end %>


</script>